spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/vdnh_back'
    username: 'postgres'
    password: 'postgres'
springdoc:
  swagger-ui:
    path: '/swagger-ui'

mapbox:
  accessToken: ''
