ALTER TABLE location_type ADD COLUMN icon_code TEXT NOT NULL DEFAULT 'UNKNOWN';

ALTER TABLE place ADD COLUMN visit_time_minutes INTEGER NOT NULL DEFAULT 15;
ALTER TABLE place ADD COLUMN placement TEXT NOT NULL DEFAULT 'OUTSIDE';
ALTER TABLE place ADD COLUMN payment_conditions TEXT NOT NULL DEFAULT 'FREE';

ALTER TABLE event ADD COLUMN visit_time_minutes INTEGER NOT NULL DEFAULT 15;
ALTER TABLE event ADD COLUMN placement TEXT NOT NULL DEFAULT 'OUTSIDE';
ALTER TABLE event ADD COLUMN payment_conditions TEXT NOT NULL DEFAULT 'TICKET';
